apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-monitor-config
  namespace: kube-system
data:
  service_config.json: |
    {
        "serviceMappings":  {
                                "example-api":  {
                                                    "appId":  "019bbdeb-3726-74ee-8f12-4502f1c1062e",
                                                    "instanceId":  "019bbdeb-4a20-7d90-af3d-a70371724579"
                                                }
                            },
        "apisecUrl":  "https://api.apisecapps.com",
        "apiKey":  "eyJraWQiOiJFUDhwZmZlYXczM05WRjU1ZU5jZTBMT3F5Z0tKTFZCOW9FSnZcLzc0ak9QQT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1NDY4ZDRmOC01MDYxLTcwMTQtODA0NS0wOTI2NDYzNTY4NWIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfN3Z6bXo1WXM1IiwiY29nbml0bzp1c2VybmFtZSI6IjU0NjhkNGY4LTUwNjEtNzAxNC04MDQ1LTA5MjY0NjM1Njg1YiIsIm9yaWdpbl9qdGkiOiIzYjhkODQ3ZS1lMWJhLTQ2ZTYtYmE1Zi1iYTBjMjZiYjQxMDIiLCJjdXN0b206dGVuYW50SWQiOiIyMTNjMGJkYi01Mzc0LTRkYzgtOWUzOC1mNWE1NGMwMDM3ODUiLCJhdWQiOiJjZ24xOWwwNHZzdWdhbTlvcDc5bmRnbThsIiwiZXZlbnRfaWQiOiJjYzU0MDNjMC00YWFiLTQ1ZDktYWJjYS00YzRlY2NhMDg4ZGEiLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTc2ODQyODA3NywibmFtZSI6IkFybmFhdiBBbmFuZCIsImV4cCI6MTc2ODQzMTY3NywiY3VzdG9tOmxpY2Vuc2UiOiJUUklBTCIsImN1c3RvbTpyb2xlIjoiVVNFUiIsImlhdCI6MTc2ODQyODA3OCwianRpIjoiOTI3NTE3NTUtMzVkOS00Yjg1LTlhZTEtZTVkNmFmNjcxZDJlIiwiZW1haWwiOiJhcm40NHZAZ21haWwuY29tIn0.lX3iforavhX6RGkROaz5JM66-qXvEDvL0TVjLICT0mWJ1vQf9PAwqsB46WKOvdvVF6W4fh1HkW-tDT6Muq5XGDiTpqav_UYIX3V10qTE45HY_oj1UZjJBqVW8oF_7Cl9RpfwtRm6blWhQMOe7hJA-8IMiCf6aPKs5YjyKkJMOeuNAap0U2zAZIDcVXYb5XDcDfIBNlkj-sqigILvnBed5gkBhmu3A1TG-F4MFjrhE4VhIQJWPSTvfhuB6s2pQgfLG1R0CQ-tQ15FmTuUDwGm_mwJ_gBw0_ja8L2f3OyBbgXSTQSTcc-Orqkqd59866Q7yghDb6NXehN-EoPIZC_dRg",
        "autoOnboardNewServices":  false
    }

