apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-monitor-config
  namespace: kube-system
data:
  service_config.json: |
    {
        "serviceMappings":  {
    
                            },
        "devApiUrl":  "https://api.dev.apisecapps.com",
        "apiKey":  "eyJraWQiOiJmV3o5UTVNeStEUEZBblpUMkFNTlwvNCszVlhHeFRXa3F1VFFyUTEreHM4TT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI0NDc4MzQyOC1iMGUxLTcwYmQtMTAzZi1jNzQzMDY3ZmFkZTMiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfZmtsU1dTU1FnIiwiY29nbml0bzp1c2VybmFtZSI6IjQ0NzgzNDI4LWIwZTEtNzBiZC0xMDNmLWM3NDMwNjdmYWRlMyIsIm9yaWdpbl9qdGkiOiI2NTk4NjIxOC02MTNiLTQ1ZjgtOTI3NC1kYjAyNjg1NzlkZGQiLCJjdXN0b206dGVuYW50SWQiOiJlMTU5MjdjOC0xZDBkLTRkZDQtYTgzOS1hZjNmNDQxMTZjNTgiLCJhdWQiOiIxamRqdnM1NnRwOG1uNDFnZjFzamE0azhpdiIsImV2ZW50X2lkIjoiZWY1YmExZDUtYjcwMy00MGQ0LTllZTUtOWVlMTEwZmM0ZTcxIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE3NjY0MzA3NzQsIm5hbWUiOiJBcm5hYXYiLCJleHAiOjE3NjY0MzQzNzcsImN1c3RvbTpsaWNlbnNlIjoiRU5URVJQUklTRSIsImN1c3RvbTpyb2xlIjoiVVNFUiIsImlhdCI6MTc2NjQzMDc3NywianRpIjoiOGJlZmQ4YTAtZTA1NS00OTdlLTljNTMtYzE0MDlkMzgwYThhIiwiZW1haWwiOiJhcm5hYXZAYXBpc2VjLmFpIn0.rSirLJckrnhqgyPtBudq6U-ScnkiEunFtQtAvTVr9siCpTzsgUPIeUt6LCJYOl-ysxvCq676JBy7GfU7JQDtH2zfTay99ejfRl1Yz_07daY69JL8Q0ufy8ed2-seB942otXEmVaEo0Jz0Q5ydwKWF-A-J88P6W2fsYyI8sehjYoTKIt4XC-wLZNLNIcQIYVO5Lzij8m8OorkIcgDQIMiQnZZEKr_dUB-TcOKY1i2KhkVrMN5MDI6iI_KrJHTd5ynQWCuar41Eyohz4fDBs9geHDZQ9DxdQ5enaL2XGokOZQd8NVepCEGmTNF5jgV5akrcPDc5dfib4g6IJsxPewMig",
        "autoOnboardNewServices":  true
    }

