apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-monitor-config
  namespace: kube-system
data:
  service_config.json: |
    {
      "apiKey": "eyJraWQiOiJmV3o5UTVNeStEUEZBblpUMkFNTlwvNCszVlhHeFRXa3F1VFFyUTEreHM4TT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI0NDc4MzQyOC1iMGUxLTcwYmQtMTAzZi1jNzQzMDY3ZmFkZTMiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfZmtsU1dTU1FnIiwiY29nbml0bzp1c2VybmFtZSI6IjQ0NzgzNDI4LWIwZTEtNzBiZC0xMDNmLWM3NDMwNjdmYWRlMyIsIm9yaWdpbl9qdGkiOiJlYWUwNzMzMy0yOGU0LTRlNzEtODM5OS0zMGFjMmM4N2VhYTMiLCJjdXN0b206dGVuYW50SWQiOiJlMTU5MjdjOC0xZDBkLTRkZDQtYTgzOS1hZjNmNDQxMTZjNTgiLCJhdWQiOiIxamRqdnM1NnRwOG1uNDFnZjFzamE0azhpdiIsImV2ZW50X2lkIjoiYWRkOWYxNjgtNTcyYi00Mzk3LWE1ZTItOTA2M2ZiODIzNmJkIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE3NjU1MjY5OTcsIm5hbWUiOiJBcm5hYXYiLCJleHAiOjE3NjU1MzA2MDgsImN1c3RvbTpsaWNlbnNlIjoiRU5URVJQUklTRSIsImN1c3RvbTpyb2xlIjoiVVNFUiIsImlhdCI6MTc2NTUyNzAwOCwianRpIjoiNDdhNWZiN2MtNjg0Yy00YzQ4LWE3MmUtMDU5ZGY4YjM0YzAyIiwiZW1haWwiOiJhcm5hYXZAYXBpc2VjLmFpIn0.XJTaoaYaSZrX1ZYI4JV1sF-ORrL3uUx7UmkJo6ek0QDkYT-iaUok-xPhqVmHuvFwKyYhErE2LyWTWyQ5-YLZD_zaMusyXYHy4qyif41XWHa2EzZTTyb1CdA-vRJgRJhtIqU6E0CuHI08Kks1ROwSwr_rtH8z0X_GJo4VvB9-6NYPh48oBdeiku_MX_0fZ2nqHX_uOmrEhqtBrR5SaiTcLHDxlQvG0kMAa_1IOClye7CxrteblUndFkeGtMkYsTaPKPq5Us_nDSTFr0XOCZBfe9DPSu9c3fNZtVFsCVvRO_tUDChJMgGUBp0BEQzJOMfKvvurOwJlILN80OQ4fY2CRA",
      "autoOnboardNewServices": true,
      "devApiUrl": "https://api.dev.apisecapps.com",
      "serviceMappings": {}
    }

