apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-monitor-config
  namespace: kube-system
data:
  service_config.json: |
    {
        "serviceMappings":  {
                                
                            },
        "devApiUrl":  "https://api.dev.apisecapps.com",
        "apiKey":  "",
        "autoOnboardNewServices":  false
    }

